#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check prettier standards
yarn check:format ||
(
  echo '
        🤢 🤢 🤢 🤢
        Prettier Check Failed.
        Run yarn format, add changes and try commit again.
        🤢 🤢 🤢 🤢
        ';
  false;
)

# Check types
yarn run check ||
(
  echo '
        😤 😤 😤 😤
        Type Check Failed.
        Make the changes above, add changes and re-try commit.
        😤 😤 😤 😤
        ';
  false;
)

yarn build ||
(
  echo '
        ❌ ❌ ❌ ❌
        Build failed: View the errors above to see why.
        ❌ ❌ ❌ ❌
        ';
  false;
)

echo '
      ✅ Prettier 
      ✅ ESLint
      ✅ Build
      All passed. Committing now.
      ';
